Repository sonr-io/snrd, pull requests merged in 2022-06, with the labels that each got.

#338 Feature/motor state machine
  go.sum
  pkg/config/config.go
  pkg/host/common.go
  pkg/host/config.go
  pkg/host/host.go
  pkg/host/host_test.go
  pkg/host/state_machine.go
Labels: Highway, Motor

#370 Created DID Query Methods
  pkg/did/document.go
  pkg/did/document_test.go
  pkg/did/interface.go
Labels: bug, enhancement, feature

#372 Add Return Methods for DID List
  pkg/did/document.go
  pkg/did/interface.go
Labels: enhancement

#382 Upgrade to cosmos v0.45.5
  .github/workflows/buf.yml
  .github/workflows/build-and-test.yml
  .github/workflows/release.yml
  .goreleaser.yaml
  app/app.go
  app/simulation_test.go
  cmd/highway-cli/highwaycmd/auth.go
  cmd/highway-cli/highwaycmd/auth_test.go
  cmd/highway-cli/highwaycmd/root.go
  cmd/sonrd/main.go
  docs/static/blockchain.yaml
  go.mod
  go.sum
  internal/highway/x/matrix/config.go
  internal/highway/x/matrix/protocol.go
  internal/highway/x/matrix/rooms.go
  pkg/did/credential.go
  pkg/did/did_test.go
  pkg/did/document.go
  pkg/host/host.go
  proto/bucket/v1/query.proto
  proto/channel/v1/query.proto
  proto/registry/v1/query.proto
  testutil/network/network.go
  x/bucket/types/query.pb.go
  x/bucket/types/query.pb.gw.go
  x/channel/types/query.pb.go
  x/channel/types/query.pb.gw.go
  x/registry/types/query.pb.go
  x/registry/types/query.pb.gw.go
Labels: dependencies

#388 [CRITICAL] Hotfix for updating blockchain genesis
  app/app.go
Labels: bug

#384 Feature/create schema
  docs/static/blockchain.yaml
  internal/highway/api/crud_schema.go
  internal/highway/highway.go
  internal/highway/x/ipfs/protocol.go
  pkg/client/cosmos.go
  pkg/did/did.go
  proto/schema/v1/query.proto
  proto/schema/v1/schema.proto
  proto/schema/v1/tx.proto
  proto/schema/v1/what_is.proto
  testutil/keeper/schema.go
  x/schema/keeper/grpc_query_schema.go
  x/schema/keeper/msg_server_schema.go
  x/schema/keeper/msg_server_schema_test.go
  x/schema/keeper/schema.go
  x/schema/module.go
  x/schema/module_simulation.go
  x/schema/simulation/createSchema.go
  x/schema/simulation/simap.go
  x/schema/types/keys.go
  x/schema/types/message_create_schema.go
  x/schema/types/query.pb.go
  x/schema/types/schema.pb.go
  x/schema/types/tx.pb.go
  x/schema/types/what_is.pb.go
Labels: Highway, Blockchain

#400 Add Metadata to WhoIs Object in Registry
  docs/static/blockchain.yaml
  go.sum
  proto/registry/v1/tx.proto
  proto/registry/v1/who_is.proto
  x/registry/keeper/msg_server_who_is.go
  x/registry/types/tx.pb.go
  x/registry/types/who_is.pb.go
Labels: enhancement
