Repository sonr-io/snrd, pull requests merged in 2022-04, with the labels that each got.

#190 Feature/ipfs
  .vscode/launch.json
  constants/status/statusCodes.go
  go.mod
  go.sum
  highway/server.go
  host/host.go
  host/option.go
  host/state.go
  ipfs/ipfs.go
  ipfs/ipfs_test.go
  ipfs/response_structs.go
Labels: feature

#188 ci: update to go version 1.17 from 1.16
  go.mod
Labels: upgrade

#208 Implement/adr 002
  channel/channel.go
  channel/handler.go
  crypto/cl/attribute.go
  crypto/cl/attribute_test.go
  crypto/cl/cred_issue_test.go
  crypto/cl/cred_manager.go
  crypto/cl/cred_manager_request.go
  crypto/cl/db_manager.go
  crypto/cl/keys.go
  crypto/cl/org.go
  crypto/cl/params.go
  crypto/cl/raw_creds.go
  crypto/cl/raw_creds_test.go
  did/jwe.go
  go.mod
  go.sum
  highway/client/cosmos.go
  highway/crud_bucket.go
  highway/crud_channel.go
  highway/crud_object.go
  highway/crud_registry.go
  highway/server.go
  host/ipfs/protocol.go
  host/ipfs/store.go
  host/matrix/protocol.go
  proto/highway/v1/highway.proto
  proto/highway/v1/request.proto
  proto/highway/v1/response.proto
  proto/host/zk/v1/messages.proto
  proto/host/zk/v1/services.proto
  zk/config/defaults.go
  zk/config/defaults.yml
  zk/log/formats.go
  zk/log/levels.go
  zk/log/logger.go
  zk/log/logger_file.go
  zk/log/logger_null.go
  zk/log/logger_stdout.go
  zk/log/logger_stdout_file.go
  zk/log/logger_test.go
  zk/server.go
  zk/util/zk_extensions.go
  zk/util/zk_translations.go
Labels: enhancement, feature

#212 Integrate/http methods
  channel/channel.go
  device/file.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  highway/client/cosmos.go
  highway/client/webauthn.go
  highway/config/config.go
  highway/config/cosmos_config.go
  highway/config/node_config.go
  highway/config/options.go
  highway/crud_blob.go
  highway/crud_bucket.go
  highway/crud_channel.go
  highway/crud_object.go
  highway/crud_object_test.go
  highway/crud_registry.go
  highway/errors.go
  highway/server.go
  host/discover/config.go
  host/discover/local.go
  host/discover/protocol.go
  host/exchange/protocol.go
  host/exchange/util.go
  host/host.go
  host/ipfs/protocol.go
  host/option.go
  host/state.go
  host/transmit/config.go
  host/transmit/item.go
  host/transmit/protocol.go
  host/transmit/session.go
  motor/config/callback.go
  proto/highway/v1/highway.proto
  proto/highway/v1/request.proto
  proto/highway/v1/response.proto
Labels: enhancement, feature
