Repository sonr-io/snrd, pull requests merged in 2025-03, with the labels that each got.

#1251 feat: enhance release process with Doppler integration
  .github/workflows/release.yml
Labels: size/XS, bugfix

#1252 feat: enhance development environment with ripgrep and gh-milestone
  devbox.json
  devbox.lock
Labels: bugfix, size/M

#1253 feature/1247
  api/did/v1/genesis.pulsar.go
  api/dwn/v1/genesis.pulsar.go
  api/svc/v1/genesis.pulsar.go
  api/svc/v1/state.cosmos_orm.go
  api/svc/v1/state.pulsar.go
  proto/did/v1/genesis.proto
  proto/dwn/v1/genesis.proto
  proto/svc/v1/genesis.proto
  proto/svc/v1/state.proto
  x/did/types/genesis.go
  x/did/types/genesis.pb.go
  x/did/types/params.go
  x/dwn/types/genesis.go
  x/dwn/types/genesis.pb.go
  x/svc/types/genesis.go
  x/svc/types/genesis.pb.go
  x/svc/types/params.go
  x/svc/types/state.pb.go
Labels: size/L, feature

#1255 feat: configure default authorization policies for DWN operators
  x/dwn/types/params.go
Labels: feature, size/M

#1245 chore: make function comment match function name
  x/did/keeper/genesis.go
  x/dwn/types/embed/codec.go
Labels: size/XS
